using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace backend.Models
{
    /// <summary>
    /// Subtype table for users who have been approved as local guides.
    /// The primary key is the same userID as the parent User row (it is not
    /// generated by the database), and Reviews.guideID has a foreign key
    /// pointing at this table, so a row must exist here before a guide can
    /// be reviewed.
    /// </summary>
    [Table("TravelGuide")]
    public class TravelGuide
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("userID")]
        public int UserID { get; set; }
    }
}
